### ISSUE TITLE
[Feat] ScrollBar Styling

### ISSUE THREAD

**Issue by MishraTanishq619** [Komsos-Matias-Rasul/webpage-samara#1]
## Description
Currently : We have the dafault styles for Scrollbar. We hadn't gave a custom styles to our scrollbar.
Expectation : We can add our custom styles to the scrollbar. So that it can be aligned with our app theme.

 I'm a Hacktoberfest'24 contributor
 I am willing to work on this issue 
Please assign this issue to me.

**Comment by PetrusAriaa** [comment]
Kindly check your Hacktoberfest progress status. Keep the good work!
